import { mkdirSync, writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { tiles, scenes, objects, avatars, palette } from '../art/herbalist.mjs';
const out=new URL('../out/art-study/',import.meta.url);mkdirSync(out,{recursive:true});
if(tiles.length>256)throw Error('Study exceeds a SCREEN 2 section pattern budget');
const patterns=[],colors=[];
for(const tile of tiles){
 patterns.push(tile.rows.map(row=>parseInt(row.replaceAll('.','0').replaceAll('#','1'),2)));
 colors.push(tile.colors.map(([fg,bg])=>fg*16+bg));
}
const spritePatterns=[];
writeFileSync(new URL('patterns.bin',out),Buffer.from(patterns.flat()));
writeFileSync(new URL('colors.bin',out),Buffer.from(colors.flat()));
for(const frame of avatars){
 if(frame.length!==16||frame.some(r=>r.length!==16||/[^.BY]/.test(r)))throw Error('Invalid avatar');
 for(const color of ['B','Y'])spritePatterns.push([0,8].flatMap(x=>frame.map(row=>parseInt(row.slice(x,x+8).split('').map(c=>+(c===color)).join(''),2))));
}
for(const scene of scenes){
 if(scene.map.length!==768||scene.collision.length!==768||scene.map.some(n=>n>=tiles.length))throw Error('Invalid scene');
}
const array=(name,rows)=>`const u8 ${name}[${rows.length}][${rows[0].length}] = {\n${rows.map(r=>` {${r.join(',')}}`).join(',\n')}\n};\n`;
writeFileSync(new URL('../art/herbalist.generated.h',import.meta.url),`// Generated by node msx/tools/art-study.mjs from art/herbalist.mjs.\n#define ART_TILE_COUNT ${tiles.length}\n${array('artPatterns',patterns)}${array('artColors',colors)}${array('artMaps',scenes.map(s=>s.map))}${array('artCollision',scenes.map(s=>s.collision))}${array('artSprites',spritePatterns)}`);
// Lossless PNG previews rendered directly from the same indexed pixels as the ROM.
const rgb=palette.map(c=>[0,2,4].map(i=>parseInt(c.slice(i,i+2),16)));
function crc(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;}return (n^0xffffffff)>>>0;}
function png(name,w,h,pixels,scale=1){
 const W=w*scale,H=h*scale,raw=Buffer.alloc(H*(W*3+1));
 for(let y=0;y<H;y++)for(let x=0;x<W;x++){const c=rgb[pixels[Math.floor(y/scale)*w+Math.floor(x/scale)]];for(let k=0;k<3;k++)raw[y*(W*3+1)+1+x*3+k]=c[k];}
 const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;};
 const hdr=Buffer.alloc(13);hdr.writeUInt32BE(W);hdr.writeUInt32BE(H,4);hdr[8]=8;hdr[9]=2;
 writeFileSync(new URL(name,out),Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',hdr),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]));
}
function drawTile(pixels,width,id,x,y){const tile=tiles[id];for(let j=0;j<8;j++)for(let i=0;i<8;i++)pixels[(y+j)*width+x+i]=tile.colors[j][tile.rows[j][i]==='#'?0:1];}
for(const [index,scene]of scenes.entries()){
 const pixels=Array(256*192).fill(1);scene.map.forEach((id,i)=>drawTile(pixels,256,id,i%32*8,Math.floor(i/32)*8));
 const ax=120,ay=index?128:112;avatars[2].forEach((r,y)=>[...r].forEach((c,x)=>{if(c!=='.')pixels[(ay+y)*256+ax+x]=c==='B'?4:11;}));
 png(`${index?'interior':'exterior'}-native.png`,256,192,pixels);png(`${index?'interior':'exterior'}-4x.png`,256,192,pixels,4);
}
const atlasHeight=Math.ceil(tiles.length/16)*8;
const atlas=Array(128*atlasHeight).fill(1);tiles.forEach((_,i)=>drawTile(atlas,128,i,i%16*8,Math.floor(i/16)*8));png('tiles-4x.png',128,atlasHeight,atlas,4);
const report={tiles:tiles.length,patternAndColorBytes:tiles.length*16,sceneMapBytes:1536,collisionBytes:1536,avatarFrames:8,avatarLayers:2,spritePatternBytes:512,maximumStudySpritesPerScanline:2,screenMode:2,scenePatterns:scenes.map(s=>({name:s.name,uniquePatterns:new Set(s.map).size})),objects:objects.map(o=>({name:o.name,category:o.category,width:o.grid[0].length,height:o.grid.length,solid:o.solid})),tileIndex:tiles.map((t,id)=>({id,name:t.name}))};
writeFileSync(new URL('budget.json',out),JSON.stringify(report,null,2)+'\n');
console.log(`Art study: ${tiles.length} valid SCREEN 2 patterns; 8 avatar frames, 2 layers; previews in msx/out/art-study`);
