import { writeFileSync } from 'node:fs';
import { OBJECT_CATALOG, SOLID_TILES } from '../../webapp/shared/catalog.ts';

// Original Village artwork. The shared catalog generates the C collision and
// footprint tables as well, preventing renderer/validator disagreement.
const blank = () => Array.from({ length: 16 }, () => Array(16).fill(0));
const rect = (p, x, y, w, h, value = 1) => {
  for (let row = y; row < y + h; row++) for (let col = x; col < x + w; col++) p[row][col] = value;
};
const background = [];
for (let kind = 0; kind < 5; kind++) {
  const p = blank();
  if (kind === 0) { // broad tree canopy and trunk
    for (let y = 1; y < 12; y++) for (let x = 0; x < 16; x++) if (Math.abs(x - 7.5) < Math.min(y + 2, 8, 15 - y)) p[y][x] = 1;
    rect(p, 6, 10, 4, 6);
  } else if (kind === 1) {
    rect(p, 1, 2, 14, 9); rect(p, 3, 4, 10, 5, 0); rect(p, 2, 11, 2, 4); rect(p, 12, 11, 2, 4);
  } else if (kind === 2) {
    rect(p, 1, 0, 14, 15); rect(p, 3, 2, 4, 3, 0); rect(p, 9, 2, 4, 3, 0); rect(p, 2, 7, 12, 1, 0); rect(p, 2, 15, 2, 1); rect(p, 12, 15, 2, 1);
  } else if (kind === 3) {
    for (const [x, y] of [[4, 4], [11, 4], [4, 11], [11, 11]]) { rect(p, x - 1, y, 3, 1); rect(p, x, y - 1, 1, 3); }
  } else { // house entrance: arch, frame, and threshold
    rect(p, 2, 2, 12, 14); rect(p, 4, 4, 8, 10, 0); rect(p, 4, 1, 8, 1); rect(p, 10, 9, 1, 1);
  }
  for (const [qx, qy] of [[0, 0], [8, 0], [0, 8], [8, 8]]) background.push(Array.from({ length: 8 }, (_, y) => p[qy + y].slice(qx, qx + 8).reduce((n, bit) => n * 2 + bit, 0)));
}
const sprites = [];
for (let avatar = 0; avatar < 4; avatar++) for (let face = 0; face < 4; face++) for (let step = 0; step < 2; step++) {
  const p = blank();
  rect(p, 5, 2, 6, 5); rect(p, 6, 7, 4, 2); rect(p, 4, 9, 8, 3);
  if (avatar === 1) rect(p, 3, 2, 10, 1);
  if (avatar === 2) { rect(p, 4, 1, 8, 1); rect(p, 3, 2, 1, 3); rect(p, 12, 2, 1, 3); }
  if (avatar === 3) { rect(p, 6, 0, 4, 2); rect(p, 3, 4, 1, 3); rect(p, 12, 4, 1, 3); }
  if (face === 0) rect(p, 6, 2, 4, 2, 0);
  else if (face === 1) { rect(p, 6, 4, 1, 1, 0); rect(p, 9, 4, 1, 1, 0); }
  else { rect(p, face === 2 ? 4 : 11, 4, 1, 2); rect(p, face === 2 ? 5 : 10, 4, 1, 1, 0); }
  rect(p, step ? 4 : 5, 12, 3, step ? 4 : 3);
  rect(p, step ? 9 : 8, 12, 3, step ? 3 : 4);
  // TMS9918 16x16 shape: all 16 left rows, then all 16 right rows.
  sprites.push([...Array.from({ length: 16 }, (_, y) => p[y].slice(0, 8).reduce((n, bit) => n * 2 + bit, 0)), ...Array.from({ length: 16 }, (_, y) => p[y].slice(8).reduce((n, bit) => n * 2 + bit, 0))]);
}
for (const size of [8, 16]) {
  const p = blank();
  rect(p, 0, 0, size, 1); rect(p, 0, size - 1, size, 1); rect(p, 0, 0, 1, size); rect(p, size - 1, 0, 1, size);
  sprites.push([...Array.from({ length: 16 }, (_, y) => p[y].slice(0, 8).reduce((n, bit) => n * 2 + bit, 0)), ...Array.from({ length: 16 }, (_, y) => p[y].slice(8).reduce((n, bit) => n * 2 + bit, 0))]);
}
const list = values => values.join(',');
writeFileSync(new URL('../assets.generated.h', import.meta.url), `// Generated by msx/tools/assets.mjs; edit the generator or shared catalog.
#define OBJECT_COUNT ${OBJECT_CATALOG.length}
const u8 objectSize[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => o.size))}};
const u8 objectSolid[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => +o.solid))}};
const u8 tileSolid[16] = {${list(Array.from({length:16}, (_, i) => +SOLID_TILES.includes(i)))}};
const char* objectNames[OBJECT_COUNT] = {${OBJECT_CATALOG.map(o => JSON.stringify(o.name.toUpperCase())).join(',')}};
const u8 largePatterns[20][8] = {${background.map(row => `{${list(row)}}`).join(',')}};
const u8 avatarPatterns[34][32] = {${sprites.map(row => `{${list(row)}}`).join(',')}};
`);
