import { writeFileSync } from 'node:fs';
import { OBJECT_CATALOG, OBJECT_CATEGORIES, TERRAIN_CATALOG } from '../../webapp/shared/catalog.ts';
import { buildArtwork } from './production-art.mjs';
const { atlas, sprites, terrainPatterns, doorPatterns, objectCells, offsets } = buildArtwork();
const list = values => values.join(',');
writeFileSync(new URL('../assets.generated.h', import.meta.url), `// Generated by msx/tools/assets.mjs; edit the generator or shared catalog.
#define OBJECT_COUNT ${OBJECT_CATALOG.length}
#define CATALOG_CAPACITY ${Math.max(OBJECT_CATALOG.length,TERRAIN_CATALOG.length)}
#define TERRAIN_COUNT ${TERRAIN_CATALOG.length}
#define ART_COUNT ${atlas.length}
#define CATEGORY_COUNT ${OBJECT_CATEGORIES.length}
const u8 objectWidth[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => o.width))}};
const u8 objectHeight[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => o.height))}};
const u8 objectCategory[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => o.category))}};
const u8 objectOffsetTable[OBJECT_COUNT] = {${list(offsets)}};
const u8 objectCells[${objectCells.length}] = {${list(objectCells)}};
const u8 objectSolid[OBJECT_COUNT] = {${list(OBJECT_CATALOG.map(o => +o.solid))}};
const u8 tileSolid[TERRAIN_COUNT] = {${list(TERRAIN_CATALOG.map(tile=>+tile.solid))}};
const u8 doorPatterns[4] = {${list(doorPatterns)}};
const u8 terrainPatterns[TERRAIN_COUNT] = {${list(terrainPatterns)}};
const char* tileNames[TERRAIN_COUNT] = {${TERRAIN_CATALOG.map(tile=>JSON.stringify(tile.name.toUpperCase())).join(',')}};
const char* categoryNames[CATEGORY_COUNT] = {${OBJECT_CATEGORIES.map(n=>JSON.stringify(n.toUpperCase())).join(',')}};
const char* objectNames[OBJECT_COUNT] = {${OBJECT_CATALOG.map(o => JSON.stringify(o.name.toUpperCase())).join(',')}};
const u8 scenePatterns[ART_COUNT][8] = {${atlas.map(t=>`{${list(t.p)}}`).join(',')}};
const u8 sceneColors[ART_COUNT][8] = {${atlas.map(t=>`{${list(t.c)}}`).join(',')}};
const u8 avatarPatterns[${sprites.length}][32] = {${sprites.map(row => `{${list(row)}}`).join(',')}};
`);
console.log(`Catalog: ${OBJECT_CATALOG.length} objects, ${atlas.length} deduplicated art patterns, ${objectCells.length} object cells`);
