import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { initialSettlement } from '../shared/settlement.ts';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const cwd = resolve(dirname(fileURLToPath(import.meta.url)),'..');
const base = process.env.VILLAGE_TEST_URL ?? 'http://127.0.0.1:5173';
if (!['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('Tests must use a local isolated database');
const suffix = randomBytes(4).toString('hex');
const tokens = Array.from({length:3},()=>randomBytes(32).toString('hex'));
const time = Math.floor(Date.now()/1000);
const sql = tokens.map(t=>`INSERT INTO invitations VALUES ('${createHash('sha256').update(t).digest('hex')}',${time},${time+3600});`).join('\n');
execFileSync(resolve(cwd,'node_modules/.bin/wrangler'),['d1','execute','DB','--local','--command',sql],{cwd,stdio:'pipe'});
async function api(path,method='GET',value,cookie='',origin=base) {
 const response = await fetch(base+path,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:value===undefined?undefined:JSON.stringify(value)});
 return {status:response.status,data:await response.json(),cookie:response.headers.get('Set-Cookie')?.split(';')[0]??''};
}
const register=(i,invite=tokens[i])=>api('/api/auth/register','POST',{username:`t${suffix}${i}`,password:'a long test password',invitation:invite});
const a=await register(0);assert.equal(a.status,201,JSON.stringify(a.data));
const b=await register(1);assert.equal(b.status,201);
assert.equal((await register(2,tokens[0])).status,409,'one invitation cannot create two accounts');
assert.equal((await api('/api/auth/login','POST',{username:`t${suffix}0`,password:'wrong'})).status,401);
assert.equal((await api('/api/auth/login','POST',{username:`t${suffix}0`,password:'a long test password'})).status,200);
assert.equal((await api('/api/plots/claim','POST',{x:0,y:0},a.cookie,'https://evil.example')).status,403);
const x=parseInt(suffix.slice(0,2),16)%100-50, y=parseInt(suffix.slice(2,4),16)%100-50;
const claims=await Promise.all([api('/api/plots/claim','POST',{x,y},a.cookie),api('/api/plots/claim','POST',{x:x+1,y},a.cookie)]);
assert.deepEqual(claims.map(c=>c.status).sort(),[201,409],'parallel claims cannot allocate two plots');
const claimed=claims.find(c=>c.status===201).data.plot;
assert.equal((await api('/api/plots/claim','POST',{x:claimed.x,y:claimed.y},b.cookie)).status,409);
assert.equal((await api('/api/settlement','PUT',{expectedRevision:0,settlement:initialSettlement()},b.cookie)).status,404,'another account cannot save the owned plot');
assert.equal((await api('/api/settlement','PUT',{expectedRevision:0,settlement:initialSettlement(),owner_id:b.data.user.id},a.cookie)).status,400);
const first=initialSettlement();first.exterior[0]=7;
const saves=await Promise.all([api('/api/settlement','PUT',{expectedRevision:0,settlement:first},a.cookie),api('/api/settlement','PUT',{expectedRevision:0,settlement:initialSettlement()},a.cookie)]);
assert.deepEqual(saves.map(c=>c.status).sort(),[200,409]);
const me=await api('/api/me','GET',undefined,a.cookie);assert.equal(me.data.plot.revision,1);
assert.equal((await api('/api/settlement','PUT',{expectedRevision:1,settlement:{...initialSettlement(),exterior:[0]}},a.cookie)).status,400);
assert.equal((await api('/api/settlement','PUT',{expectedRevision:1,settlement:{...initialSettlement(),x:claimed.x+1}},a.cookie)).status,400);
assert.equal((await api('/api/settlement','PUT',{expectedRevision:1,settlement:initialSettlement()})).status,401);
const romResponse=await fetch(base+'/api/snapshot.rom',{headers:{Cookie:a.cookie}});
assert.equal(romResponse.status,200);const rom=new Uint8Array(await romResponse.arrayBuffer());
assert.equal(rom.length,1048576);assert.deepEqual(Array.from(rom.slice(32768,32772)),[77,83,88,86]);assert.equal(rom[32776],40);assert.equal(rom[(5+40)*8192+16],me.data.plot.content.exterior[0],'fresh snapshot recovers persisted tiles');
assert.equal(new TextDecoder().decode(rom).includes(a.data.user.id),false,'snapshot excludes account identity');
const guest=new Uint8Array(await (await fetch(base+'/api/snapshot.rom')).arrayBuffer());assert.equal(guest[32776],255,'guest ROM must have no editable plot');
assert.equal((await api('/api/auth/logout','POST',{},a.cookie)).status,200);
assert.equal((await api('/api/me','GET',undefined,a.cookie)).data.user,null);
console.log('PASS: invitations, passwords, CSRF, concurrent claims, ownership, stale saves, ROM snapshots, logout');
