// Stable catalog IDs. Existing IDs 0–7 retain their original one-tile size.
export const OBJECT_CATALOG = [
  { name: 'Tree', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Table', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Chair', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Bed', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Lamp', width: 1, height: 1, category: 0, art: null, solid: false },
  { name: 'Plant pot', width: 1, height: 1, category: 0, art: null, solid: false },
  { name: 'Bookcase', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Chest', width: 1, height: 1, category: 0, art: null, solid: true },
  { name: 'Large tree', width: 2, height: 2, category: 0, art: null, solid: true },
  { name: 'Dining table', width: 2, height: 2, category: 0, art: null, solid: true },
  { name: 'Double bed', width: 2, height: 2, category: 0, art: null, solid: true },
  { name: 'Flower patch', width: 2, height: 2, category: 0, art: null, solid: false },
  { name: 'Old oak', width: 5, height: 5, category: 1, solid: true, art: 'Old oak' },
  { name: 'Pine', width: 3, height: 4, category: 1, solid: true, art: 'Pine' },
  { name: 'Orchard tree', width: 3, height: 3, category: 1, solid: true, art: 'Orchard tree' },
  { name: 'Well', width: 2, height: 2, category: 2, solid: true, art: 'Well' },
  { name: 'Shrine', width: 1, height: 2, category: 4, solid: true, art: 'Shrine' },
  { name: 'Cottage bed', width: 2, height: 2, category: 3, solid: true, art: 'Bed' },
  { name: 'Oak table', width: 2, height: 2, category: 3, solid: true, art: 'Table' },
  { name: 'Hearth', width: 2, height: 2, category: 3, solid: true, art: 'Hearth' },
  { name: 'Herbs', width: 1, height: 1, category: 1, solid: false, art: 'herbs' },
  { name: 'Flowers', width: 1, height: 1, category: 1, solid: false, art: 'flower' },
  { name: 'Pot', width: 1, height: 1, category: 1, solid: false, art: 'pot' },
  { name: 'Hanging sign', width: 1, height: 1, category: 2, solid: true, art: 'sign' },
  { name: 'Bookshelf', width: 1, height: 1, category: 3, solid: true, art: 'shelf' },
  { name: 'Bottles', width: 1, height: 1, category: 3, solid: false, art: 'bottles' },
  { name: 'Cottage chair', width: 1, height: 1, category: 3, solid: true, art: 'chair' },
  { name: 'Wooden chest', width: 1, height: 1, category: 3, solid: true, art: 'chest' },
  { name: 'Cottage roof', width: 6, height: 2, category: 2, solid: true, art: 'Cottage roof' },
  { name: 'Cottage wall', width: 2, height: 3, category: 2, solid: true, art: 'Cottage wall' },
] as const;
export const OBJECT_CATEGORIES = ['Classic', 'Garden', 'Village', 'Interior', 'Relics'] as const;
export const SOLID_TILES = [2, 3, 4, 5, 9, 10, 11, 14, 15];
export const DOOR_SIZE = 2;
